### ISSUE TITLE
Detect blocks of changed code

### ISSUE THREAD

**Issue by koogle** [chrisma/marvin#7]

**Comment by chrisma** [comment]
Find out which lines are above and below a block.
- [ ] function that determines whether line is blame-worthy, e.g. not '', not 'end'

**Comment by koogle** [comment]
Evaluate metrics for importance and complexity of a line of code

**Comment by chrisma** [comment]
For every changed line it is sufficient to recognize a maximum of 2 interesting lines, those above and below the modified line.

**Comment by chrisma** [comment]
What happens in a file full of blank lines and an edit in between?
Need to rely on full file from blame

**Comment by koogle** [comment]
Moved this to marvin parser
